fix: make subprocess exit set started state
If an `ipfsd-daemon` instance connects to a running API it does not have a
`this.subprocess` property, yet if we try to stop the node it tries to access
that property, leading to this sort of error:

```
  2) DelegatedPeerRouting
       "after all" hook in "DelegatedPeerRouting":
     TypeError: Cannot read property 'stderr' of null
      at Daemon.stop (node_modules/ipfsd-ctl/src/ipfsd-daemon.js:260:21)
      at processTicksAndRejections (node:internal/process/task_queues:93:5)
      at async Promise.all (index 0)
```

This PR moves `this.subprocess` access to where it is created and lets the
process exiting set `this.started` to `false` as otherwise the state can
get out of sync with reality.